language: java
jdk:
- openjdk8
addons:
        sonarcloud:
                organization: "francesco1997"
                token:
                  secure: "J2WwOuP7RrcCpm2E8RcWTUd6PcNVXGqnBkPZy+oVy1/L9+bZxeB/qYfp4QPWYPq2am9regPn5J1WZJS7YJNeJQdtlbWq8E/TVuuIA8yc2WBD1RSOMPLv5sUmKYylLE1r7jswMzBWPodbmdGbWbkdgm5oL/tG/BDAbTEXAracNBPpCORCbGuv4B54kd1hkC5+yd1cdGlXbsk7b0pNTSKC8Xmkhh5n9ZKLeVh2lY8kwBeTz5WVdhxFJ7MrCm3/g6sF5ua4IxvDJ/Hx1eH74LupyKCAmEqB5KvocX/L4aVGfE6qy09IBSNbkULwn83OjQe1PG19QK39jsaIG8v/Qdqk3RHvErVYn6+r2KkwsWgsVc6KOEI9xqT1HkevISlqH2MJ4EtlHCbaBMoJcgUTiJL05CRhLxYvYFyvZNQJ06aMrUS+dIq562yppIoBx3zKP8h2vJ+tj7KtBagwoK2hfoVZNqEAuvncFIpzuS4kVZaj4OkLflQUTOEGWdQhwIoKMxBZsYGKZ8qAwxp3iPn5/IbWUzfWoxzFPVL5LiJawwiRnRHuLB6GLzqGkhBXsFmD+QMkMB2wTPas/e6M7dfblLDq30qIR7WXMjO5k6w007kymgzxbOWpdWzRK8Rfvp+JtHCLVYdTbAEkJ3Qt61GNhVKN97gfO0GFM5KZsokZ4ADet2k="
script: 
        - ant build
        - sonar-scanner
